version: '3.8'

services:

  ugovws-pf:
    tty: true
    build:
      context: .
      network: host
    image: python3.8.ugovws-api-pf
    network_mode: "host"
    volumes:
      - ./app:/app
      - .env:/app/.env
    environment:
      - WEB_CONCURRENCY=3
      - PORT=8022
    ports:
      - "8022:8022"
    restart: 'always'


  test-ugovws-pf:
    tty: true
    build:
      context: .
      network: host
    image: python3.8.ugovws-api-pf_test
    network_mode: "host"
    volumes:
      - ./app:/app
      - .env-test:/app/.env
    environment:
      - WEB_CONCURRENCY=1
      - PORT=9022
    ports:
      - "9022:9022"
    restart: 'always'